[theme]

# Primary accent for interactive elements
primaryColor = '#C2FFB7'

# Background color for the main content area
backgroundColor = '#7F3300'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#FF6A00'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "monospace"
